name: test-application
region: fra1
services:
  - name: web
    image:
      registry_type: "DOCR"
      repository: "test-application"
      tag: "latest"
      deploy_on_push: true
    instance_size_slug: basic-xxs
    instance_count: 1
    routes:
      - path: /
    envs:
      - key: LISTEN_PORT
        value: "8080"
