version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t test-application .
      - run:
          name: Authenticate to DigitalOcean Container Registry
          command: echo $DIGITALOCEAN_ACCESS_TOKEN | docker login -u $DIGITALOCEAN_USERNAME --password-stdin registry.digitalocean.com
      - run:
          name: Push Docker image to DigitalOcean Container Registry
          command: docker tag test-application registry.digitalocean.com/test-application/test-application:latest && docker push registry.digitalocean.com/test-application/test-application:latest

workflows:
  build_deploy:
    jobs:
      - build:
          context:
            - account-digitalocean
          filters:
            branches:
              only:
                - master