version: 2.1

orbs:
  doctl: digitalocean/cli@1.0.0
  docker: circleci/docker@3.5.0

jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - docker/setup:
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: docker build -t test-application .
      - run:
          name: Authenticate to DigitalOcean Container Registry
          command: echo $DIGITALOCEAN_ACCESS_TOKEN | docker login -u $DIGITALOCEAN_USERNAME --password-stdin registry.digitalocean.com
      - run:
          name: Push Docker image to DigitalOcean Container Registry
          command: docker tag test-application registry.digitalocean.com/test-application/test-application:latest && docker push registry.digitalocean.com/test-application/test-application:latest

workflows:
  build_deploy:
    jobs:
      - build:
          context:
            - account-digitalocean
          filters:
            branches:
              only:
                - master
      - deploy:
          name: deploy-api
          context:
            - account-digitalocean
          filters:
            branches:
              only:
                - master
          requires:
            - build